target_name: "浪潮信息"
stock_code: "000977"
target_type: 'financial_company'  # financial_company, macro, industry, general
output_dir: "./outputs/exp-v1"
language: 'zh' # zh,en
reference_doc_path: 'src/template/report_template.docx' # used for docx style
outline_template_path: 'src/template/company_outline_zh.md' # used for outline style

custom_collect_tasks:

custom_analysis_tasks:


use_collect_data_cache: True
use_analysis_cache: True
use_report_outline_cache: True
use_full_report_cache: True
use_post_process_cache: True

# load in environment variables
llm_config_list:
  - model_name: "${DS_MODEL_NAME}"
    api_key: "${DS_API_KEY}"
    base_url: "${DS_BASE_URL}"
    generation_params:
      temperature: 0.7
      max_tokens: 32768
      top_p: 0.95
  - model_name: "${EMBEDDING_MODEL_NAME}"
    api_key: "${EMBEDDING_API_KEY}"
    base_url: "${EMBEDDING_BASE_URL}"
  - model_name: "${VLM_MODEL_NAME}"
    api_key: "${VLM_API_KEY}"
    base_url: "${VLM_BASE_URL}"